@startuml
class ArticleEntity {
    + Id : int <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Author : string <<get>> <<set>>
}
Dates <|-- ArticleEntity
IArticle <|-- ArticleEntity
ArticleEntity --> "Type" ContentTypeEntity
@enduml
