@startuml
class DataContext {
    + DataContext(options:DbContextOptions<DataContext>)
}
class "DbSet`1"<T> {
}
DbContext <|-- DataContext
DataContext --> "ContentTypes<ContentTypeEntity>" "DbSet`1"
DataContext --> "Articles<ArticleEntity>" "DbSet`1"
@enduml
